
INSERT INTO "AZ_TEST.DB".AZ_TEST.DEPARTMENT (ID,CODE, "NAME") 
	VALUES (1,'az', 'Азбука');
INSERT INTO "AZ_TEST.DB".AZ_TEST."USER" (ID,"NAME", DEPARTMENT_ID) 
	VALUES (1,'Иванов', 1);
INSERT INTO "AZ_TEST.DB".AZ_TEST.DEPARTMENT_USER (DEPARTMENT_ID, USERS_ID) 
	VALUES (1, 1);